# -*- coding: utf-8 -*-
"""
v2 预置网站库：100+ 常用网站。

字段说明（见 TRAE 设计稿 附录 C）：
- id          唯一标识
- name        展示名
- category    game/video/chat/dev/social/shopping/knowledge/overseas
- icon        SVG 图标键名
- host        测试主机名/IP
- port        测试端口
- test_type   ["ping","tcp","dns","http","iperf"]
- region      domestic/overseas
- weight      排序权重 0-100
- suggested_test   默认主打测试
- fallback         失效备选 id 列表
- data_updated     验证日期 YYYY-MM-DD
"""

from datetime import date

VERIFIED_DATE = "2026-08-20"

# ============================================================================
# 预置目标库：100+ 目标
# ============================================================================
PRESET_TARGETS = [
    # ------------------------------------------------------------------------
    # 游戏 (game) - 25 个
    # ------------------------------------------------------------------------
    {
        "id": "tx-lol",
        "name": "腾讯·英雄联盟",
        "category": "game",
        "icon": "lol",
        "host": "lobby.na1.lol.pvp.net",
        "port": 2099,
        "test_type": ["ping", "tcp"],
        "region": "domestic",
        "weight": 95,
        "suggested_test": "ping",
        "fallback": ["tx-lol-alt"],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "tx-lol-alt",
        "name": "腾讯·英雄联盟(备用)",
        "category": "game",
        "icon": "lol",
        "host": "game.qq.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 60,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "tx-honor",
        "name": "腾讯·王者荣耀",
        "category": "game",
        "icon": "honor",
        "host": "hdl2.qq.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 94,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "tx-peace",
        "name": "腾讯·和平精英",
        "category": "game",
        "icon": "peace",
        "host": "gp.qq.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 90,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "tx-dnf",
        "name": "腾讯·DNF",
        "category": "game",
        "icon": "dnf",
        "host": "dnf.qq.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 85,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "netease-mc",
        "name": "网易·我的世界",
        "category": "game",
        "icon": "minecraft",
        "host": "mc.netease.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 80,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "netease-ys",
        "name": "网易·永劫无间",
        "category": "game",
        "icon": "yjw",
        "host": "naraka.qq.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 78,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "miyabi",
        "name": "米哈游·原神",
        "category": "game",
        "icon": "genshin",
        "host": "ys-api.mihoyo.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 93,
        "suggested_test": "http",
        "fallback": ["miyabi-cn"],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "miyabi-cn",
        "name": "米哈游·崩坏：星穹铁道",
        "category": "game",
        "icon": "starrail",
        "host": "api-beta.mihoyo.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 85,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "miyabi-sr",
        "name": "米哈游·绝区零",
        "category": "game",
        "icon": "zzz",
        "host": "zzz-api.mihoyo.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 80,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "steam-download",
        "name": "Steam·下载节点",
        "category": "game",
        "icon": "steam",
        "host": "cm2-ord1.cm.steampowered.com",
        "port": 443,
        "test_type": ["tcp", "http"],
        "region": "overseas",
        "weight": 92,
        "suggested_test": "tcp",
        "fallback": ["steam-cdn"],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "steam-cdn",
        "name": "Steam·全球 CDN",
        "category": "game",
        "icon": "steam",
        "host": "cdn.steamcommunity.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 75,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "epic",
        "name": "Epic Games",
        "category": "game",
        "icon": "epic",
        "host": "epicgames-download1.ak.epicgames.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 75,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "blizzard",
        "name": "暴雪战网",
        "category": "game",
        "icon": "blizzard",
        "host": "cn.blizzard.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 78,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "riot",
        "name": "Riot Games",
        "category": "game",
        "icon": "riot",
        "host": "na1.api.riotgames.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 70,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "valorant",
        "name": "Valorant",
        "category": "game",
        "icon": "valorant",
        "host": "na-1.na.a.pvp.net",
        "port": 7000,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 72,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "cs2",
        "name": "Counter-Strike 2",
        "category": "game",
        "icon": "cs2",
        "host": "cs2-core.cs2stats.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 75,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "dota2",
        "name": "DOTA 2",
        "category": "game",
        "icon": "dota2",
        "host": "d2east.blob.core.windows.net",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 70,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "pubg",
        "name": "PUBG",
        "category": "game",
        "icon": "pubg",
        "host": "matchmaker.playbattlegrounds.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 72,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "playstation",
        "name": "PlayStation",
        "category": "game",
        "icon": "psn",
        "host": "psn.hyp.sony.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 65,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "xbox",
        "name": "Xbox Live",
        "category": "game",
        "icon": "xbox",
        "host": "xboxlive.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 60,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "netease-onmyoji",
        "name": "网易·阴阳师",
        "category": "game",
        "icon": "onmyoji",
        "host": "yys.163.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 70,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "netease-identity",
        "name": "网易·第五人格",
        "category": "game",
        "icon": "identity",
        "host": "idv.163.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 72,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "wegame",
        "name": "WeGame 平台",
        "category": "game",
        "icon": "wegame",
        "host": "www.wegame.com.cn",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 80,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "hypergryph",
        "name": "鹰角网络·明日方舟",
        "category": "game",
        "icon": "arknights",
        "host": "ak-api.hypergryph.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 75,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },

    # ------------------------------------------------------------------------
    # 视频 (video) - 20 个
    # ------------------------------------------------------------------------
    {
        "id": "bilibili-api",
        "name": "B站·接口",
        "category": "video",
        "icon": "bilibili",
        "host": "api.bilibili.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 95,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "bilibili-upload",
        "name": "B站·视频上传",
        "category": "video",
        "icon": "bilibili",
        "host": "up-na02.bilibili.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 90,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "bilibili-cdn",
        "name": "B站·视频播放 CDN",
        "category": "video",
        "icon": "bilibili",
        "host": "cn-hk-eqx-bcache-01.bilivideo.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 88,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "youku",
        "name": "优酷",
        "category": "video",
        "icon": "youku",
        "host": "v.youku.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 80,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "iqiyi",
        "name": "爱奇艺",
        "category": "video",
        "icon": "iqiyi",
        "host": "www.iqiyi.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 80,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "tencent-video",
        "name": "腾讯视频",
        "category": "video",
        "icon": "txvideo",
        "host": "v.qq.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 78,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "mango",
        "name": "芒果 TV",
        "category": "video",
        "icon": "mgtv",
        "host": "www.mgtv.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 65,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "youtube",
        "name": "YouTube",
        "category": "video",
        "icon": "youtube",
        "host": "www.youtube.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 88,
        "suggested_test": "http",
        "fallback": ["google"],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "youtube-cdn",
        "name": "YouTube CDN",
        "category": "video",
        "icon": "youtube",
        "host": "googlevideo.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 78,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "netflix",
        "name": "Netflix",
        "category": "video",
        "icon": "netflix",
        "host": "www.netflix.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 75,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "disney",
        "name": "Disney+",
        "category": "video",
        "icon": "disney",
        "host": "www.disneyplus.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 65,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "twitch",
        "name": "Twitch",
        "category": "video",
        "icon": "twitch",
        "host": "www.twitch.tv",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 70,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "douyin",
        "name": "抖音",
        "category": "video",
        "icon": "douyin",
        "host": "www.douyin.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 90,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "kuaishou",
        "name": "快手",
        "category": "video",
        "icon": "kuaishou",
        "host": "www.kuaishou.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 80,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "vimeo",
        "name": "Vimeo",
        "category": "video",
        "icon": "vimeo",
        "host": "vimeo.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 55,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "tiktok",
        "name": "TikTok",
        "category": "video",
        "icon": "tiktok",
        "host": "www.tiktok.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 70,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "qqmusic",
        "name": "QQ 音乐",
        "category": "video",
        "icon": "qqmusic",
        "host": "y.qq.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 70,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "netease-music",
        "name": "网易云音乐",
        "category": "video",
        "icon": "music163",
        "host": "music.163.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 72,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "spotify",
        "name": "Spotify",
        "category": "video",
        "icon": "spotify",
        "host": "open.spotify.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 65,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "acfun",
        "name": "AcFun",
        "category": "video",
        "icon": "acfun",
        "host": "www.acfun.cn",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 60,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },

    # ------------------------------------------------------------------------
    # 通讯 (chat) - 15 个
    # ------------------------------------------------------------------------
    {
        "id": "wechat",
        "name": "微信",
        "category": "chat",
        "icon": "wechat",
        "host": "wx.qq.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 95,
        "suggested_test": "http",
        "fallback": ["wechat-cdn"],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "wechat-cdn",
        "name": "微信·CDN",
        "category": "chat",
        "icon": "wechat",
        "host": "wxsns.qq.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 80,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "qq",
        "name": "QQ",
        "category": "chat",
        "icon": "qq",
        "host": "www.qq.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 92,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "dingtalk",
        "name": "钉钉",
        "category": "chat",
        "icon": "dingtalk",
        "host": "www.dingtalk.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 88,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "wework",
        "name": "企业微信",
        "category": "chat",
        "icon": "wework",
        "host": "work.weixin.qq.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 85,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "feishu",
        "name": "飞书",
        "category": "chat",
        "icon": "feishu",
        "host": "www.feishu.cn",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 82,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "discord",
        "name": "Discord",
        "category": "chat",
        "icon": "discord",
        "host": "discord.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 72,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "telegram",
        "name": "Telegram",
        "category": "chat",
        "icon": "telegram",
        "host": "web.telegram.org",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 70,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "zoom",
        "name": "Zoom",
        "category": "chat",
        "icon": "zoom",
        "host": "zoom.us",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 70,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "teams",
        "name": "Microsoft Teams",
        "category": "chat",
        "icon": "teams",
        "host": "teams.microsoft.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 65,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "slack",
        "name": "Slack",
        "category": "chat",
        "icon": "slack",
        "host": "slack.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 65,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "line",
        "name": "LINE",
        "category": "chat",
        "icon": "line",
        "host": "line.me",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 55,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "whatsapp",
        "name": "WhatsApp",
        "category": "chat",
        "icon": "whatsapp",
        "host": "web.whatsapp.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 60,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "kakao",
        "name": "KakaoTalk",
        "category": "chat",
        "icon": "kakao",
        "host": "www.kakaocorp.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 50,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "skype",
        "name": "Skype",
        "category": "chat",
        "icon": "skype",
        "host": "www.skype.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 50,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },

    # ------------------------------------------------------------------------
    # 开发 (dev) - 15 个
    # ------------------------------------------------------------------------
    {
        "id": "github",
        "name": "GitHub",
        "category": "dev",
        "icon": "github",
        "host": "github.com",
        "port": 443,
        "test_type": ["tcp", "http"],
        "region": "overseas",
        "weight": 95,
        "suggested_test": "tcp",
        "fallback": ["github-fastly"],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "github-fastly",
        "name": "GitHub Pages",
        "category": "dev",
        "icon": "github",
        "host": "github.io",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 75,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "gitlab",
        "name": "GitLab",
        "category": "dev",
        "icon": "gitlab",
        "host": "gitlab.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 78,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "gitee",
        "name": "Gitee",
        "category": "dev",
        "icon": "gitee",
        "host": "gitee.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 82,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "npm",
        "name": "npm Registry",
        "category": "dev",
        "icon": "npm",
        "host": "registry.npmjs.org",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 80,
        "suggested_test": "tcp",
        "fallback": ["npm-mcn"],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "npm-mcn",
        "name": "npm 淘宝镜像",
        "category": "dev",
        "icon": "npm",
        "host": "registry.npmmirror.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 75,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "pypi",
        "name": "PyPI",
        "category": "dev",
        "icon": "python",
        "host": "pypi.org",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 78,
        "suggested_test": "tcp",
        "fallback": ["pypi-tsinghua"],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "pypi-tsinghua",
        "name": "PyPI 清华镜像",
        "category": "dev",
        "icon": "python",
        "host": "pypi.tuna.tsinghua.edu.cn",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 80,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "stackoverflow",
        "name": "Stack Overflow",
        "category": "dev",
        "icon": "stackoverflow",
        "host": "stackoverflow.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 72,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "dockerhub",
        "name": "Docker Hub",
        "category": "dev",
        "icon": "docker",
        "host": "registry-1.docker.io",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 78,
        "suggested_test": "tcp",
        "fallback": ["docker-cn"],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "docker-cn",
        "name": "Docker 阿里云镜像",
        "category": "dev",
        "icon": "docker",
        "host": "registry.cn-hangzhou.aliyuncs.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "domestic",
        "weight": 75,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "openai",
        "name": "ChatGPT (OpenAI)",
        "category": "dev",
        "icon": "openai",
        "host": "api.openai.com",
        "port": 443,
        "test_type": ["tcp", "http"],
        "region": "overseas",
        "weight": 88,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "anthropic",
        "name": "Claude (Anthropic)",
        "category": "dev",
        "icon": "anthropic",
        "host": "api.anthropic.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 80,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "huggingface",
        "name": "Hugging Face",
        "category": "dev",
        "icon": "huggingface",
        "host": "huggingface.co",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 65,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "kaggle",
        "name": "Kaggle",
        "category": "dev",
        "icon": "kaggle",
        "host": "www.kaggle.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 55,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },

    # ------------------------------------------------------------------------
    # 社交 (social) - 10 个
    # ------------------------------------------------------------------------
    {
        "id": "weibo",
        "name": "微博",
        "category": "social",
        "icon": "weibo",
        "host": "www.weibo.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 88,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "zhihu",
        "name": "知乎",
        "category": "social",
        "icon": "zhihu",
        "host": "www.zhihu.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 80,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "xiaohongshu",
        "name": "小红书",
        "category": "social",
        "icon": "xhs",
        "host": "www.xiaohongshu.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 82,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "twitter",
        "name": "Twitter / X",
        "category": "social",
        "icon": "twitter",
        "host": "twitter.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 75,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "facebook",
        "name": "Facebook",
        "category": "social",
        "icon": "facebook",
        "host": "www.facebook.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 70,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "instagram",
        "name": "Instagram",
        "category": "social",
        "icon": "instagram",
        "host": "www.instagram.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 68,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "reddit",
        "name": "Reddit",
        "category": "social",
        "icon": "reddit",
        "host": "www.reddit.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 60,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "tieba",
        "name": "百度贴吧",
        "category": "social",
        "icon": "tieba",
        "host": "tieba.baidu.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 65,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "douban",
        "name": "豆瓣",
        "category": "social",
        "icon": "douban",
        "host": "www.douban.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 60,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "linkedin",
        "name": "LinkedIn",
        "category": "social",
        "icon": "linkedin",
        "host": "www.linkedin.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 55,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },

    # ------------------------------------------------------------------------
    # 购物 (shopping) - 8 个
    # ------------------------------------------------------------------------
    {
        "id": "taobao",
        "name": "淘宝",
        "category": "shopping",
        "icon": "taobao",
        "host": "www.taobao.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 92,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "jd",
        "name": "京东",
        "category": "shopping",
        "icon": "jd",
        "host": "www.jd.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 90,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "pdd",
        "name": "拼多多",
        "category": "shopping",
        "icon": "pdd",
        "host": "www.pinduoduo.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 85,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "1688",
        "name": "1688",
        "category": "shopping",
        "icon": "1688",
        "host": "www.1688.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 75,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "tmall",
        "name": "天猫",
        "category": "shopping",
        "icon": "tmall",
        "host": "www.tmall.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 88,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "amazon-cn",
        "name": "亚马逊海外购",
        "category": "shopping",
        "icon": "amazon",
        "host": "www.amazon.cn",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 65,
        "suggested_test": "http",
        "fallback": ["amazon-us"],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "amazon-us",
        "name": "Amazon.com",
        "category": "shopping",
        "icon": "amazon",
        "host": "www.amazon.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 60,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "ebay",
        "name": "eBay",
        "category": "shopping",
        "icon": "ebay",
        "host": "www.ebay.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 50,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },

    # ------------------------------------------------------------------------
    # 知识 (knowledge) - 5 个
    # ------------------------------------------------------------------------
    {
        "id": "baidu",
        "name": "百度",
        "category": "knowledge",
        "icon": "baidu",
        "host": "www.baidu.com",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 88,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "wikipedia",
        "name": "维基百科",
        "category": "knowledge",
        "icon": "wikipedia",
        "host": "zh.wikipedia.org",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 70,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "juejin",
        "name": "掘金",
        "category": "knowledge",
        "icon": "juejin",
        "host": "juejin.cn",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 72,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "csdn",
        "name": "CSDN",
        "category": "knowledge",
        "icon": "csdn",
        "host": "www.csdn.net",
        "port": 443,
        "test_type": ["http"],
        "region": "domestic",
        "weight": 70,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "bing",
        "name": "Bing 搜索",
        "category": "knowledge",
        "icon": "bing",
        "host": "cn.bing.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 65,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },

    # ------------------------------------------------------------------------
    # 海外 (overseas) - 12 个
    # ------------------------------------------------------------------------
    {
        "id": "google",
        "name": "Google",
        "category": "overseas",
        "icon": "google",
        "host": "www.google.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 95,
        "suggested_test": "http",
        "fallback": ["google-apis"],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "google-apis",
        "name": "Google APIs",
        "category": "overseas",
        "icon": "google",
        "host": "apis.google.com",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 78,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "cloudflare",
        "name": "Cloudflare",
        "category": "overseas",
        "icon": "cloudflare",
        "host": "www.cloudflare.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 88,
        "suggested_test": "http",
        "fallback": ["cloudflare-1dot1dot1dot1"],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "cloudflare-1dot1dot1dot1",
        "name": "Cloudflare 1.1.1.1",
        "category": "overseas",
        "icon": "cloudflare",
        "host": "1.1.1.1",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 80,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "aws",
        "name": "AWS",
        "category": "overseas",
        "icon": "aws",
        "host": "aws.amazon.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 72,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "azure",
        "name": "Microsoft Azure",
        "category": "overseas",
        "icon": "azure",
        "host": "azure.microsoft.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 70,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "apple",
        "name": "Apple",
        "category": "overseas",
        "icon": "apple",
        "host": "www.apple.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 75,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "microsoft",
        "name": "Microsoft",
        "category": "overseas",
        "icon": "microsoft",
        "host": "www.microsoft.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 72,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "wikipedia-en",
        "name": "Wikipedia (en)",
        "category": "overseas",
        "icon": "wikipedia",
        "host": "en.wikipedia.org",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 65,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "duckduckgo",
        "name": "DuckDuckGo",
        "category": "overseas",
        "icon": "duckduckgo",
        "host": "duckduckgo.com",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 55,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "github-pages",
        "name": "GitHub Pages",
        "category": "overseas",
        "icon": "github",
        "host": "*.github.io",
        "port": 443,
        "test_type": ["tcp"],
        "region": "overseas",
        "weight": 65,
        "suggested_test": "tcp",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
    {
        "id": "speedtest",
        "name": "Speedtest.net",
        "category": "overseas",
        "icon": "speedtest",
        "host": "www.speedtest.net",
        "port": 443,
        "test_type": ["http"],
        "region": "overseas",
        "weight": 60,
        "suggested_test": "http",
        "fallback": [],
        "data_updated": VERIFIED_DATE,
    },
]


# ============================================================================
# 工具函数
# ============================================================================
def get_targets() -> list:
    """返回所有预置目标（按 weight 倒序）"""
    return sorted(PRESET_TARGETS, key=lambda t: -t.get("weight", 0))


def get_target(target_id: str) -> dict | None:
    """按 ID 获取目标"""
    for t in PRESET_TARGETS:
        if t["id"] == target_id:
            return t
    return None


def filter_by_category(category_id: str) -> list:
    """按分类筛选目标"""
    return [t for t in PRESET_TARGETS if t["category"] == category_id]


def get_default_targets(n: int = 5, scenario: str = "general") -> list:
    """获取一键全测的默认目标集合"""
    # 根据场景选择高权重目标
    if scenario == "game":
        return [t for t in PRESET_TARGETS if t["category"] == "game"][:n]
    if scenario == "video":
        return [t for t in PRESET_TARGETS if t["category"] == "video"][:n]
    if scenario == "overseas":
        return [t for t in PRESET_TARGETS if t["category"] == "overseas"][:n]

    # general: 选 weight 最高的 n 个
    return get_targets()[:n]


def get_stale_targets(days: int = 90) -> list:
    """获取 data_updated 超过 N 天的目标（需要重新验证）"""
    today = date.today()
    stale = []
    for t in PRESET_TARGETS:
        try:
            d = date.fromisoformat(t.get("data_updated", "2024-01-01"))
            if (today - d).days > days:
                stale.append(t)
        except (ValueError, TypeError):
            stale.append(t)
    return stale